variable "userdata" {
  default = "PHBvd2Vyc2hlbGw+ClN0YXJ0LVRyYW5zY3JpcHQ7CgojYWxsb3dzIGluaXRpYWxpemF0aW9uIG9mIHVzZXJkYXRhIHNjcmlwdCB3aGVuIHJlc3RhcnRlZC4KQzpcUHJvZ3JhbURhdGFcQW1hem9uXEVDMi1XaW5kb3dzXExhdW5jaFxTY3JpcHRzXHVzZXJkYXRhLnBzMSDigJNTY2hlZHVsZQoKI2NyZWF0ZSBuZXcgaW5kZXguaHRtbCBmaWxlCk5ldy1JdGVtIC1QYXRoICJDOlxpbmV0cHViXHd3d3Jvb3RcIiAtTmFtZSAiaW5kZXguaHRtbCIgLUl0ZW1UeXBlICJmaWxlIiAtVmFsdWUgIkhlbGxvIGZyb20gdGVycmFmb3JtIgoKIyBpbnN0YWxsIElJUwpJbXBvcnQtTW9kdWxlIFNlcnZlck1hbmFnZXI7CkVuYWJsZS1XaW5kb3dzT3B0aW9uYWxGZWF0dXJlIC1PbmxpbmUgLU5vUmVzdGFydCAtRmVhdHVyZU5hbWUgJ0lJUy1XZWJTZXJ2ZXJSb2xlJywgJ0lJUy1XZWJTZXJ2ZXInLCAnSUlTLU1hbmFnZW1lbnRDb25zb2xlJzsKI2NoYW5nZSBkZWZhdWx0IGlpcyBwYWdlIHRvIGluZGV4Lmh0bWwKU2V0LUl0ZW1Qcm9wZXJ0eSAnSUlTOlxTaXRlc1xEZWZhdWx0IFdlYiBTaXRlXCcgLW5hbWUgcGh5c2ljYWxQYXRoIC12YWx1ZSAiQzpcaW5ldHB1Ylx3d3dyb290XGluZGV4Lmh0bWwiCgoKPHBlcnNpc3Q+dHJ1ZTwvcGVyc2lzdD4KPC9wb3dlcnNoZWxsPg=="
  type = string
}

variable "image_id_webserver1" {
  default = "ami-08ebce687207a7730"
  type = string

}

variable "name_webserver" {
  default = {
    staging = "webserver_staging"
    production = "webserver_production"
  }
}